name:  Continuous Integration

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.txt'
      - '*.pdf'
      - '**.md'
  pull_request:
    branches:
      - master

env:
  TestMeetingOrganiserDesktopApp_Project_Path: TestMeetingOrganiserDesktopApp\TestMeetingOrganiserDesktopApp.csproj
  TestServicesForDesktopApp_Project_Path: TestServicesForDesktopApp\TestServicesForDesktopApp.csproj
  TestWebAppForMembers_Project_Path: TestWebAppForMembers\TestWebAppForMembers.csproj
  MeetingOrganiserDesktopApp_Folder: MeetingOrganiserDesktopApp
  ServicesForDesktopApp_Project_Folder: ServicesForDesktopApp
  WebAppForMembers_Project_Folder: WebAppForMembers
  DotnetVersion: '3.1.x'

jobs:

  setup:
    name: Compute Changes
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - shell: pwsh
        id: determine_testsuite # Step will be referenced later
        run: |
          $diff = git diff --name-only HEAD^ HEAD
          $SourceDiff = $diff | Where-Object { $_ -match '^CommonData/' -or $_ -match '^.github/workflows/' -or $_ -match '^.github/workflows/'}
          $HasCommonDiff = $SourceDiff.Length -gt 0
          $MustTestDesktopApp = $HasCommonDiff
          $MustTestServicesForDesktopApp = $HasCommonDiff
          $MustTestWebAppForMembers = $HasCommonDiff
          
          if (-not $HasCommonDiff){
            $SourceDiff = $diff | Where-Object { $_ -match '^${{env.MeetingOrganiserDesktopApp_Folder}}/'}
            $MustTestDesktopApp = $SourceDiff.Length -gt 0
            $MustTestServicesForDesktopApp = $MustTestDesktopApp
            
            if (-not $MustTestDesktopApp){
              $SourceDiff = $diff | Where-Object { $_ -match '^Test${{env.MeetingOrganiserDesktopApp_Folder}}'}
              $MustTestDesktopApp = $SourceDiff.Length -gt 0
  
              $SourceDiff = $diff | Where-Object { $_ -match '^${{env.ServicesForDesktopApp_Project_Folder}}/' -or $_ -match '^Test${{env.ServicesForDesktopApp_Project_Folder}}/'}
              $MustTestServicesForDesktopApp = $SourceDiff.Length -gt 0
            }
          
            $SourceDiff = $diff | Where-Object { $_ -match '^${{env.WebAppForMembers_Project_Folder}}/' -or $_ -match '^Test${{env.WebAppForMembers_Project_Folder}}/'}
            $MustTestWebAppForMembers = $SourceDiff.Length -gt 0
          }
          echo "test_desktop_app=$MustTestDesktopApp" >> "$GITHUB_OUTPUT"
          echo "::set-output name=test_services_for_desktop_app::$MustTestServicesForDesktopApp"
          echo "::set-output name=test_web_app::$MustTestWebAppForMembers"
          

  unit_test_desktop_app:
    name: Unit Test Desktop App
    needs:
      - setup
    if: $${{needs.setup.steps.determine_testsuite.outputs.test_desktop_app == 'True'}}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DotnetVersion}}
      - name: Execute Unit Tests
        run: dotnet test ${{env.TestMeetingOrganiserDesktopApp_Project_Path}}

  integration_test_desktop_app_and_services:
    name: Integration Test Desktop App with Services
    needs:
      - setup
    if: $${{needs.setup.steps.determine_testsuite.outputs.test_services_for_desktop_app == 'True'}}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DotnetVersion}}
      - name: Execute Integration Tests
        run: dotnet test ${{env.TestServicesForDesktopApp_Project_Path}}

  unit_test_web_app:
    name: Test Web App
    needs:
      - setup
    if: $${{needs.setup.steps.determine_testsuite.outputs.test_web_app == 'True'}}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DotnetVersion}}
      - name: Execute Unit Tests
        run: dotnet test ${{env.TestWebAppForMembers_Project_Path}}