name:  Continuous Integration

on:
  push:
    paths-ignore:
      - '*.txt'
      - '*.pdf'
      - '**.md'
  pull_request:
    branches:
      - master

env:
  TestMeetingOrganiserDesktopApp_Project_Path: TestMeetingOrganiserDesktopApp\TestMeetingOrganiserDesktopApp.csproj
  TestServicesForDesktopApp_Project_Path: TestServicesForDesktopApp\TestServicesForDesktopApp.csproj
  TestWebAppForMembers_Project_Path: TestWebAppForMembers\TestWebAppForMembers.csproj
  MeetingOrganiserDesktopApp_Project_Path: MeetingOrganiserDesktopApp\MeetingOrganiserDesktopApp.csproj
  ServicesForDesktopApp_Project_Path: ServicesForDesktopApp\ServicesForDesktopApp.csproj
  WebAppForMembers_Project_Path: WebAppForMembers\WebAppForMembers.csproj
  MeetingOrganiserDesktopApp_Folder: MeetingOrganiserDesktopApp
  ServicesForDesktopApp_Project_Folder: ServicesForDesktopApp
  WebAppForMembers_Project_Folder: WebAppForMembers
  DotnetVersion: '3.1.x'
  Platform: 'win-x64'
  MeetingOrganiserDesktopApp_PublishFolder: MeetingOrganiserDesktopApp/bin/Release/netcoreapp3.1/win-x64/publish
  ServicesForDesktopApp_PublishFolder: ServicesForDesktopApp/bin/Release/netcoreapp3.1/win-x64/publish
  WebAppForMembers_PublishFolder: WebAppForMembers/bin/Release/netcoreapp3.1/win-x64/publish

jobs:

  deploy_services_for_desktop_app:
    if: startsWith(github.ref, 'refs/tags/')
    permissions: write-all
    name: Deploy Services for Desktop App
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DotnetVersion}}
      - run: dotnet restore ${{ env.ServicesForDesktopApp_Project_Path }}
      - run: dotnet build ${{ env.ServicesForDesktopApp_Project_Path }} -c Release --no-restore -p:PublishSingleFile=true
      - run: dotnet publish ${{ env.ServicesForDesktopApp_Project_Path }} -c Release --self-contained -r ${{env.Platform}} -p:PublishSingleFile=true --no-build
      - uses: softprops/action-gh-release@v2
        with:
          files: $${{env.ServicesForDesktopApp_PublishFolder}}/*.exe